# -*- coding: utf-8 -*-
"""B20BB047_Task1_Lab8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vUdyywUKglMgSNNFFjOOhfBePBkcZd1E
"""

import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt

from google.colab import files
uploaded = files.upload()

df= pd.read_csv('milk.csv')
print(df.shape)
df.head()

# 'Unnamed: 0' is kind of like the label, hence we don't consider it during application of kmeans
X = df.drop(columns=['Unnamed: 0']).to_numpy()

from sklearn.cluster import KMeans

for n in [3,5,7]:
  kmeans = KMeans(n_clusters=n, random_state = 2021)
  kmeans.fit(X)
  print(kmeans.cluster_centers_)
  clusters = kmeans.predict(X)
  plt.scatter(df.water, df.protein, c=clusters)
  plt.show()

